# travis-ci.com is currently not used,
# and this file may be outdated.
#
# GitHub Actions are used: configured via
# the files in the directory:
# `.github/workflows/`
git:
  depth: 3

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

addons:
  apt:
    packages:
      - inkscape
      - texlive
      - texlive-xetex

install:
  - pip install --upgrade pip setuptools
  # svglatex
  - pip install .

script:
  - cd tests/
  - make all
